<a href="https://colab.research.google.com/github/brumbab-code/MIS433/blob/main/Copy_of_assignment_IMDB_manipulation_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In this assignment, you will be working with this dataset of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [2]:
import pandas as pd
import numpy as np

To read the data file from your Google Drive, mount your drive first.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# Read the data file "imdb_top_1000.csv" to a dataframe named "imdb"
imdb = pd.read_csv('/content/drive/MyDrive/MIS433/imdb_top_1000.csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [5]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [6]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [7]:
# Display Series_Title, Released_Year, and IMDB_Rating of the top 10 movies.
(
imdb
[['Series_Title','Released_Year','IMDB_Rating']]
.sort_values('IMDB_Rating', ascending=False)
.head(10)
)

                                     Series_Title Released_Year  IMDB_Rating
0                        The Shawshank Redemption          1994          9.3
1                                   The Godfather          1972          9.2
4                                    12 Angry Men          1957          9.0
2                                 The Dark Knight          2008          9.0
3                          The Godfather: Part II          1974          9.0
5   The Lord of the Rings: The Return of the King          2003          8.9
7                                Schindler's List          1993          8.9
6                                    Pulp Fiction          1994          8.9
8                                       Inception          2010          8.8
12                Il buono, il brutto, il cattivo          1966          8.8

In [12]:
# Display movies ranked 11-20.
# Show their Series_Title, Released_Year, and IMDB_Rating.

(
imdb
[['Series_Title','Released_Year','IMDB_Rating']]
.sort_values('IMDB_Rating', ascending=False)
.iloc[10:20]
)

,Series_Title,Released_Year,IMDB_Rating
11,Forrest Gump,1994,8.8
10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8
9,Fight Club,1999,8.8
14,The Matrix,1999,8.7
13,The Lord of the Rings: The Two Towers,2002,8.7
15,Goodfellas,1990,8.7
17,One Flew Over the Cuckoo's Nest,1975,8.7
16,Star Wars: Episode V - The Empire Strikes Back,1980,8.7
28,The Silence of the Lambs,1991,8.6
19,Gisaengchung,2019,8.6

In [13]:
# Select all movies directed by Quentin Tarantino.
# Show their Series_Title, Released_Year, IMDB_Rating, and Gross.

df1= imdb[['Series_Title','Released_Year','IMDB_Rating','Gross','Director']]
df1[df1['Director']=='Quentin Tarantino']

,Series_Title,Released_Year,IMDB_Rating,Gross,Director
6,Pulp Fiction,1994,8.9,"107,928,762",Quentin Tarantino
62,Django Unchained,2012,8.4,"162,805,434",Quentin Tarantino
93,Inglourious Basterds,2009,8.3,"120,540,719",Quentin Tarantino
103,Reservoir Dogs,1992,8.3,"2,832,029",Quentin Tarantino
241,Kill Bill: Vol. 1,2003,8.1,"70,099,045",Quentin Tarantino
369,Kill Bill: Vol. 2,2004,8.0,"66,208,183",Quentin Tarantino
584,The Hateful Eight,2015,7.8,"54,117,416",Quentin Tarantino
879,Once Upon a Time... in Hollywood,2019,7.6,"142,502,728",Quentin Tarantino

In [14]:
# Select all R rated movies with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and IMDB_Rating.

df1= imdb[['Series_Title', 'Released_Year', 'Certificate','IMDB_Rating']]
df1[(df1['IMDB_Rating']>=8.5) & (df1['Certificate']=="R")]

           Series_Title Released_Year Certificate  IMDB_Rating
24  Saving Private Ryan          1998           R          8.6
38          The Pianist          2002           R          8.5
40   American History X          1998           R          8.5

In [15]:
# How many unique values are there in the column "Released_Year"?
# Hint: nunique()

imdb['Released_Year'].nunique()

100

In [16]:
# Count the number of movies in each "Released_Year".
# Hint: value_counts()

imdb['Released_Year'].value_counts(
)

Released_Year
2014    32
2004    31
2009    29
2013    28
2016    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [17]:
# In this dataset, there is a movie with an error in "Released_Year".
# Hint: Released_Year should be a 4-digit integer but this movie's year is not.
# Find this movie.
imdb[imdb['Released_Year']=="PG"]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [18]:
# Correct the values for the corresponding columns ("Released_Year" and "Certificate").
# You may want to look up this movie on www.imdb.com.
# Hint: You can set value for a particular row by: df.loc[row_index, column_name] = new_value

imdb.loc[966,'Released_Year'] = '1995'
imdb.loc[966, 'Certificate'] = 'PG'
imdb.loc[[966],:]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,1995,PG,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [19]:
# Change the data type of "Released_Year" to int

imdb['Released_Year'] = imdb['Released_Year'].astype(int)
imdb['Released_Year']

0      1994
1      1972
2      2008
3      1974
4      1957
       ...
995    1961
996    1956
997    1953
998    1944
999    1935
Name: Released_Year, Length: 1000, dtype: int64

In [20]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and IMDB_Rating.

df1 = imdb[['Series_Title','Released_Year','Certificate','IMDB_Rating']]
df1[(df1['Released_Year']>=2010) & (df1['IMDB_Rating']>=8.5)]

        Series_Title  Released_Year Certificate  IMDB_Rating
8          Inception           2010          UA          8.8
18          Hamilton           2020       PG-13          8.6
19      Gisaengchung           2019           A          8.6
20   Soorarai Pottru           2020           U          8.6
21      Interstellar           2014          UA          8.6
33             Joker           2019           A          8.5
34          Whiplash           2014           A          8.5
35  The Intouchables           2011          UA          8.5

In [21]:
# Select all movies whose genres contain 'Animation'

df1= imdb[['Series_Title','Released_Year','IMDB_Rating','Gross','Director','Genre']]
df1[df1['Genre'].str.contains('Animation')]

,Series_Title,Released_Year,IMDB_Rating,Gross,Director,Genre
23,Sen to Chihiro no kamikakushi,2001,8.6,"10,055,859",Hayao Miyazaki,"Animation, Adventure, Family"
43,The Lion King,1994,8.5,"422,783,777",Roger Allers,"Animation, Adventure, Drama"
46,Hotaru no haka,1988,8.5,NaN,Isao Takahata,"Animation, Drama, War"
56,Kimi no na wa.,2016,8.4,"5,017,246",Makoto Shinkai,"Animation, Drama, Fantasy"
58,Spider-Man: Into the Spider-Verse,2018,8.4,"190,241,310",Bob Persichetti,"Animation, Action, Adventure"
...,...,...,...,...,...,...
956,Mulan,1998,7.6,"120,620,254",Tony Bancroft,"Animation, Adventure, Family"
971,Omohide poro poro,1991,7.6,"453,243",Isao Takahata,"Animation, Drama, Romance"
976,The Little Mermaid,1989,7.6,"111,543,479",Ron Clements,"Animation, Family, Fantasy"
986,Watership Down,1978,7.6,NaN,Martin Rosen,"Animation, Adventure, Drama"
992,The Jungle Book,1967,7.6,"141,843,612",Wolfgang Reitherman,"Animation, Adventure, Family"

In [22]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4

stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']]
stars

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen
996,Giant,1956,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker
997,From Here to Eternity,1953,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed
998,Lifeboat,1944,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix
999,The 39 Steps,1935,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle

In [23]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.

genres = imdb[['Series_Title','Released_Year','Genre']]
genres

                 Series_Title  Released_Year                     Genre
0    The Shawshank Redemption           1994                     Drama
1               The Godfather           1972              Crime, Drama
2             The Dark Knight           2008      Action, Crime, Drama
3      The Godfather: Part II           1974              Crime, Drama
4                12 Angry Men           1957              Crime, Drama
..                        ...            ...                       ...
995    Breakfast at Tiffany's           1961    Comedy, Drama, Romance
996                     Giant           1956            Drama, Western
997     From Here to Eternity           1953       Drama, Romance, War
998                  Lifeboat           1944                Drama, War
999              The 39 Steps           1935  Crime, Mystery, Thriller

[1000 rows x 3 columns]

In [24]:
# Sorting:
# Sort the genres dataframe in ascending order of "Released_Year"

genres.sort_values('Released_Year')

                     Series_Title  Released_Year                         Genre
321  Das Cabinet des Dr. Caligari           1920      Fantasy, Horror, Mystery
127                       The Kid           1921         Comedy, Drama, Family
568                     Nosferatu           1922               Fantasy, Horror
194                  Sherlock Jr.           1924       Action, Comedy, Romance
193                 The Gold Rush           1925      Adventure, Comedy, Drama
..                            ...            ...                           ...
612    The Trial of the Chicago 7           2020      Drama, History, Thriller
613                          Druk           2020                 Comedy, Drama
20                Soorarai Pottru           2020                         Drama
18                       Hamilton           2020     Biography, Drama, History
205                          Soul           2020  Animation, Adventure, Comedy

[1000 rows x 3 columns]

In [25]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and Gross.
# Sort them in descending order of "Gross"



df1 = imdb[['Series_Title', 'Released_Year', 'Certificate', 'Gross','IMDB_Rating']]
(
df1[(df1['Released_Year']>=2010) & (df1['IMDB_Rating']>=8.5)].sort_values('Gross', ascending=False)
[['Series_Title', 'Released_Year', 'Certificate', 'Gross']]
)

        Series_Title  Released_Year Certificate        Gross
19      Gisaengchung           2019           A   53,367,844
33             Joker           2019           A  335,451,311
8          Inception           2010          UA  292,576,195
21      Interstellar           2014          UA  188,020,017
35  The Intouchables           2011          UA   13,182,281
34          Whiplash           2014           A   13,092,000
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [ ]:
# Does the sorting result look right to you? What's the problem?

#Gisaengchung is not the highest grossed movie, but it is sorted as the highest.
#The problem is the data type for gross is identified as an object when it should be identified as aa float. Since it is text, Panas sorts it by character, so 53,367,844 comes before 335,451,311, since 5 comes after 3.

In [26]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe

imdb['Gross'] = imdb['Gross'].str.replace(',','').astype(float)
imdb['Gross']

0       28341469.0
1      134966411.0
2      534858444.0
3       57300000.0
4        4360000.0
          ...
995            NaN
996            NaN
997     30500000.0
998            NaN
999            NaN
Name: Gross, Length: 1000, dtype: float64

In [27]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and Gross.
# Sort them in descending order of "Gross"

df1 = imdb[['Series_Title', 'Released_Year', 'Certificate', 'Gross','IMDB_Rating']]
(
df1[(df1['Released_Year']>=2010) & (df1['IMDB_Rating']>=8.5)].sort_values('Gross', ascending=False)
[['Series_Title', 'Released_Year', 'Certificate', 'Gross']]
)

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [28]:
# Add a new column "Runtime_min" by removing the substring " min" in "Runtime"
# Set its data type as int
# Hint: https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe

imdb['Runtime_min'] = imdb['Runtime'].str.replace('min','').astype(int)
imdb['Runtime_min']

0      142
1      175
2      152
3      202
4       96
      ...
995    115
996    201
997    118
998     97
999     86
Name: Runtime_min, Length: 1000, dtype: int64

In [29]:
imdb['Runtime_min']=imdb['Runtime'].str[:-4].astype(int)
imdb['Runtime_min']

0      142
1      175
2      152
3      202
4       96
      ...
995    115
996    201
997    118
998     97
999     86
Name: Runtime_min, Length: 1000, dtype: int64

In [30]:
# Add a new column "Age_Years" by the expression: Current year - Released_Year

imdb['Age_Years'] = 2026 - imdb['Released_Year']
imdb['Age_Years']

0      32
1      54
2      18
3      52
4      69
       ..
995    65
996    70
997    73
998    82
999    91
Name: Age_Years, Length: 1000, dtype: int64

In [31]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.

imdb['Decade'] = (imdb['Released_Year'].astype(str).str[:-1] + '0').astype(int)
imdb[['Decade','Released_Year']]

     Decade  Released_Year
0      1990           1994
1      1970           1972
2      2000           2008
3      1970           1974
4      1950           1957
..      ...            ...
995    1960           1961
996    1950           1956
997    1950           1953
998    1940           1944
999    1930           1935

[1000 rows x 2 columns]

## Part 2: Data Summarization

In [ ]:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross',
       'Runtime_min', 'Age_Years', 'Decade'],
      dtype='object')

In [32]:
# Total "Gross" of all top 1000 movies
imdb['Gross'].sum()

np.float64(56536877976.0)

In [33]:
# Average "No_of_Votes" of all movies
imdb['No_of_Votes'].mean()

np.float64(273692.911)

In [34]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order

(
imdb
.groupby('Decade')
.agg({'Series_Title':'count'})
.sort_values('Series_Title',ascending=False)
)

        Series_Title
Decade
2010             242
2000             237
1990             151
1980              89
1970              76
1960              73
1950              56
1940              35
1930              24
1920              11
2020               6

In [35]:
# Count movies by different directors.
# Show the top 10 directors with the most movies in this list

(
    imdb
    .groupby('Director')
    .agg({'Series_Title': 'count'})
    .sort_values('Series_Title', ascending=False)
    .head(10)
)

                  Series_Title
Director
Alfred Hitchcock            14
Steven Spielberg            13
Hayao Miyazaki              11
Martin Scorsese             10
Akira Kurosawa              10
Stanley Kubrick              9
Woody Allen                  9
Billy Wilder                 9
David Fincher                8
Clint Eastwood               8

In [36]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross.
# Rank them in descending order of total gross
# Show the top 10 directors with the highest total gross

(
    imdb.groupby('Director')
    .agg({'Series_Title':'count',
          'IMDB_Rating':'mean',
          'Gross':'sum'})
    .sort_values('Gross', ascending=False)
    .head(10)
)

                   Series_Title  IMDB_Rating         Gross
Director
Steven Spielberg             13     8.030769  2.478133e+09
Anthony Russo                 4     8.075000  2.205039e+09
Christopher Nolan             8     8.462500  1.937454e+09
James Cameron                 5     8.080000  1.748237e+09
Peter Jackson                 5     8.400000  1.597312e+09
J.J. Abrams                   3     7.833333  1.423171e+09
Brad Bird                     4     7.900000  1.099628e+09
Robert Zemeckis               5     8.120000  1.049446e+09
David Yates                   3     7.800000  9.789537e+08
Pete Docter                   4     8.125000  9.393821e+08

In [37]:
# Group movies by decade and director
# In each group (i.e., for each decade and each director),
# calculate the number of movies and average IMDB rating.
# Sort in descending order of movie count

(
    imdb
    .groupby(['Decade','Director'])
    .agg({'Series_Title': 'count',
          'IMDB_Rating':'mean'})
    .sort_values('Series_Title', ascending=False)
)

                             Series_Title  IMDB_Rating
Decade Director
1950   Billy Wilder                     6     8.133333
       Akira Kurosawa                   5     8.260000
2010   Denis Villeneuve                 5     7.980000
1950   Alfred Hitchcock                 5     8.220000
1980   Steven Spielberg                 5     7.980000
...                                   ...          ...
2010   Tyler Nilson                     1     7.600000
       Umesh Shukla                     1     8.100000
       Vikas Bahl                       1     8.200000
       Vikramaditya Motwane             1     8.200000
       Vishal Bhardwaj                  1     8.100000

[749 rows x 2 columns]

In [38]:
# Find the top 3 highest rated movies of each year since 2010.
# Show their released year, ranking, title, and IMDB_Rating.
# Sort them in descending order of year and ascending order of ranking

imdb['ranking'] = imdb.groupby('Released_Year')['IMDB_Rating'].rank(ascending=False, method='first')

(
    imdb[(imdb['ranking']<=3) & (imdb['Released_Year']>=2010)]
    [['Released_Year','ranking','Series_Title','IMDB_Rating']]
    .sort_values(['Released_Year','ranking'], ascending=[False,True])
)

     Released_Year  ranking                       Series_Title  IMDB_Rating
18            2020      1.0                           Hamilton          8.6
20            2020      2.0                    Soorarai Pottru          8.6
205           2020      3.0                               Soul          8.1
19            2019      1.0                       Gisaengchung          8.6
33            2019      2.0                              Joker          8.5
59            2019      3.0                  Avengers: Endgame          8.4
53            2018      1.0                         Capharnaüm          8.4
58            2018      2.0  Spider-Man: Into the Spider-Verse          8.4
60            2018      3.0             Avengers: Infinity War          8.4
54            2017      1.0          Ayla: The Daughter of War          8.4
55            2017      2.0                       Vikram Vedha          8.4
61            2017      3.0                               Coco          8.4
56            2016      1.0                     Kimi no na wa.          8.4
57            2016      2.0                             Dangal          8.4
196           2016      3.0                               Pink          8.1
133           2015      1.0                             Talvar          8.2
136           2015      2.0                           Drishyam          8.2
203           2015      3.0                               Room          8.1
21            2014      1.0                       Interstellar          8.6
34            2014      2.0                           Whiplash          8.5
200           2014      3.0                              Mommy          8.1
87            2013      1.0                           Drishyam          8.3
137           2013      2.0                              Queen          8.2
138           2013      3.0                        Mandariinid          8.2
62            2012      1.0                   Django Unchained          8.4
63            2012      2.0              The Dark Knight Rises          8.4
88            2012      3.0                             Jagten          8.3
35            2011      1.0                   The Intouchables          8.5
89            2011      2.0            Jodaeiye Nader az Simin          8.3
144           2011      3.0                            Warrior          8.2
8             2010      1.0                          Inception          8.8
90            2010      2.0                          Incendies          8.3
141           2010      3.0                              Udaan          8.2

In [39]:
# Find all directors whose movies appeared in at least five different decades.
# Your result should include: director, decade, and the number of movies in the decade.

df1=(
    imdb
    .groupby(['Director','Decade'])
    .agg({'Series_Title':'count'})
    .reset_index()
)

df2 =(
    df1
    .groupby('Director')
    .agg({'Decade':'count'})
    .query('Decade >= 5')
)

df1[df1['Director'].isin(df2.index)]

             Director  Decade  Series_Title
247    Hayao Miyazaki    1970             1
248    Hayao Miyazaki    1980             4
249    Hayao Miyazaki    1990             2
250    Hayao Miyazaki    2000             3
251    Hayao Miyazaki    2010             1
424   Martin Scorsese    1970             1
425   Martin Scorsese    1980             3
426   Martin Scorsese    1990             2
427   Martin Scorsese    2000             1
428   Martin Scorsese    2010             3
644  Steven Spielberg    1970             2
645  Steven Spielberg    1980             5
646  Steven Spielberg    1990             3
647  Steven Spielberg    2000             2
648  Steven Spielberg    2010             1

In [45]:
# Ask two questions about this dataset and write your code to answer them.
# Question 1:

#Which decade produces the highest average gross?

(
    imdb
    .groupby('Decade')
    .agg({'Gross': 'mean','Series_Title':'count'})
    .sort_values('Gross', ascending=False)
)

               Gross  Series_Title
Decade
2010    1.037204e+08           242
2000    6.965808e+07           237
1980    6.231487e+07            89
1990    6.202864e+07           151
1970    5.287953e+07            76
1960    3.163478e+07            73
1930    1.840348e+07            24
1950    1.417469e+07            56
1940    8.293462e+06            35
1920    1.844978e+06            11
2020             NaN             6

In [48]:
# Question 2:

#Which actors appear the most often as the lead actor?

(
    imdb
    .groupby('Star1')
    .agg({'Series_Title':'count'})
    .sort_values('Series_Title', ascending=False)
)

                   Series_Title
Star1
Tom Hanks                    12
Robert De Niro               11
Clint Eastwood               10
Al Pacino                    10
Leonardo DiCaprio             9
...                         ...
Gérard Jugnot                 1
Günes Sensoy                  1
Haluk Bilginer                1
Harriet Andersson             1
Graham Chapman                1

[660 rows x 1 columns]